version: "3.9"

services:
  ovenmediaengine:
    image: airensoft/ovenmediaengine:latest
    restart: unless-stopped
    ports:
      - "1935:1935/tcp"
      - "3333:3333/tcp"
      - "3334:3334/tcp"
      - "9999:9999/udp"
      - "3478:3478/tcp"
      - "10000-10009:10000-10009/udp"
    volumes:
      - ./ome/conf:/opt/ovenmediaengine/bin/origin_conf
